### ISSUE TITLE
Can't install because ping probes are blocked on network

### ISSUE THREAD

**Issue by xrisk** [deadhead420/anarchy-linux#431]
Any solution other than reverting to an old commit which downloads a file to check connectivity?

**Comment by Marksion08** [comment]
I had tried many times but failed.

With the ENV: 
VirtualBox-5.1.28-117968-Win
archlinux-2017.09.01-x86_64.iso

PopUp Message as flow:
1. "Errors: No network connection exiting installer." ( But ping was fine, eg: ping www.bing.com -c 3 )
2. iptest step, network test failed.

It will be grateful so much if someone could doing help.

Thanks,
Marksion H

**Comment by pnedkov** [comment]
@xrisk , a few months ago I changed the connection check from `ping -c1 8.8.8.8` to `wget -q --spider google.com` because people were complaining about ICMP being blocked in their network. Then another group of people pointed out that google.com is blocked in their country so we changed it to `wget -q --spider github.com`. And 3 weeks ago @deadhead420 changed it back to `ping google.com -W 2 -c 1` which will not work for both groups of people mentioned above. IMO wget/curl check via HTTP/s would be a better approach. I could easily fix that but I would like to hear what the owner has to say.

I would not recommend reverting the whole git tree to an old commit just to get the old connection check. Many improvements were made since then. Just open the file and manually alter the connection check line. You can ping your gateway or wget/curl a site of your choice... whatever you want.

@Marksion08 it looks to me that your problem is different. Currently in iptest and arch-anywhere installer `ping google.com` is used for a network check. You can ping bing.com but not google.com? Is this what you are saying?

**Comment by shiz0** [comment]
Temporary fix / workaround:
Open "/usr/lib/arch-anywhere/configure_connection.sh"
in your favourite editor (vim/nano/whatever) and change "ping google.com -W 2 -c 1" to e.g. "curl heise.de", or to whatever works best on you network/location.
If you want the "iptest" utility to also work, do the same in "/usr/bin/iptest".

**Comment by danne2** [comment]
I'm having the same issue. Hopped onto a VPN to bypass it.

**Comment by deadhead420** [comment]
I changed it to check /sys/class/net/* for an interface with an active connection. This should bypass any issues with ping or wget. Testing...

**Comment by deadhead420** [comment]
Should be fixed now
