### ISSUE TITLE
Possibility to make swap partition

### ISSUE THREAD

**Issue by aaaaadrien** [deadhead420/anarchy-linux#445]
Hi,
When i am at partition step, if i create a partition with cfdisk (without select the swap type), it's not possible to define after the possibility to make swap.

It's possible to mount all parts, format them but is it possible to add at mountpoint window, the label "swap" to make a partition as swap (and format them or not) ?

Thanks

**Comment by pnedkov** [comment]
In `Manual Partition Drive` you are supposed to create all the partitions you need and their type in cfdisk. Only in cfdisk you should ever alter the partition scheme! This offloads a lot of code from the installer to cfdisk. I believe this is by design and it is a good decision that it was implemented that way. Adding code in the installer that duplicates a functionality that you already have in cfdisk which you closed a second ago does not sound right to me.

If you realize you want to change your partition scheme after you have quit cfdisk, you can run fdisk/cfdisk in another terminal and perform the changes. Then go back to the terminal where you have invoked the installer and return 1 or more steps back in the menu and select `Manual Partition Drive`. The installer will rescan the new partition scheme and display it. And you should be able to proceed.

HTH
