### ISSUE TITLE
Ftp server activation is asked even if you don't select it.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#464]
A bug I noticed since Arch-anywhere 2.2.9. If you select any server in server category, you're automatically asked for ftp server activation.

I have to answer no every single time.

**Comment by pnedkov** [comment]
A while ago I stepped on that trap as well and actually started to fix it. This is how I discovered it is not a bug. All installations have `/usr/bin/ftpd` which comes from `inetutils` package. You are being asked whether you want the ftp server to start on boot despite the fact that you have not checked `vsftpd`, because you already have an ftp server installed - `/usr/bin/ftpd`.

**Comment by FredBezies** [comment]
So, if it is not a bug, but an annoying feature, let's close it.
