### ISSUE TITLE
anarchy-1.0.0-x86_64 Install issues.

### ISSUE THREAD

**Issue by gmcclins** [deadhead420/anarchy-linux#576]
Unable to install gui version on my hypervisor. I installed using the CLI image and got no errors (except awesome and mate were not option anymore). Using the CLI iso I successfully installed an image with LVM encryption and with xfce. Install went along with no errors and I booted into no problem.

Unfortunately, I did not have the same luck with GUI iso. First error during bootup

![1 bootup](https://user-images.githubusercontent.com/1461924/34618810-f5838a04-f20d-11e7-8a1f-6e9bb2085ee9.PNG)

I then get into the live environment and receive an error about X

![2 failedstartx](https://user-images.githubusercontent.com/1461924/34618832-0747133c-f20e-11e7-895c-448b2d8060d0.PNG)

I try to install but it wants sudo

![3 sudo needed](https://user-images.githubusercontent.com/1461924/34618845-105b8494-f20e-11e7-9775-457570c94557.PNG)

So I give it sudo and it launches and I get as far as partition disk and am halted.

![4 partition error](https://user-images.githubusercontent.com/1461924/34618856-1d771b0c-f20e-11e7-8f06-39a207022293.PNG)

I'm still seeding both ISO's but I suspect the gui one is faulted somehow.

**Comment by nastybuttler322** [comment]
The GUI version of the iso that I downloaded, the one that I opened the keyboard and mouse issue for, looks different. 

I just realized that  the image you showed me for the keyboard and ouse issue, was that first image from here. I read it a little more carefully this time. It is not the same messages. My messages say "modules" instead of "Variables."

I downloaded the image directly from the website.  I have not tried the image from the torrent yet, it was taking way too long to download. It's still downloading because I forgot to open Transmission back up until now.

The website image does not have that CLI menu, and it boots directly into a desktop GUI.

**Comment by gmcclins** [comment]
yeah. I used the desktop image here, but x failed to start and it reverted to look like CLI but with issues.

**Comment by includes08** [comment]
I have the same problem @gmcclins it has something to do with x missing some stuff, i have not much time to look into it. I'm atm looking into the problems of the CLI which has a lot to since the V1 release somehow. I'm using my laptop instead of a vm cause there are more issues that way to find :). GPU related there are a lot. Which is another problem of the GUI one. I just skipped it because as far as it goes back to CLI its not functional cause you can't connect wifi somehow.

**Comment by gmcclins** [comment]
yeah, I only have hyper-v at the moment and I have zero issues with CLI. I can even successfully make a CLI image using the create script. I have yet to successfully build a GUI install or get one to work using the image made available.

**Comment by includes08** [comment]
i keep on getting stuck at the end i think linux hardened is not a thing anymore? 

http://termbin.com/ofaw

**Comment by gmcclins** [comment]
Looks like a network issue to me

`downloading linux-hardened-4.14.12.a-1-x86_64.pkg.tar.xz...
error: failed retrieving file 'linux-hardened-4.14.12.a-1-x86_64.pkg.tar.xz' from mirror.ams1.nl.leaseweb.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'linux-hardened-4.14.12.a-1-x86_64.pkg.tar.xz' from mirror.osbeck.com : Could not resolve host: mirror.osbeck.com
error: failed retrieving file 'linux-hardened-4.14.12.a-1-x86_64.pkg.tar.xz' from mirror.i3d.net : Could not resolve host: mirror.i3d.net
error: failed retrieving file 'linux-hardened-4.14.12.a-1-x86_64.pkg.tar.xz' from mirror.koddos.net : Could not resolve host: mirror.koddos.net
error: failed retrieving file 'linux-hardened-4.14.12.a-1-x86_64.pkg.tar.xz' from mirror.f4st.host : Could not resolve host: mirror.f4st.host
error: failed retrieving file 'linux-hardened-4.14.12.a-1-x86_64.pkg.tar.xz' from archlinux.mirror.wearetriple.com : Could not resolve host: archlinux.mirror.wearetriple.com
warning: failed to retrieve some files`

and it goes on.

**Comment by includes08** [comment]
Look better :P you're missing the funny part it downloads everything in front ...

**Comment by includes08** [comment]
Progress it passed the spotify, chrome mark. And it just keeps installing fine. Its really the hardened version that fails ^^'

**Comment by gmcclins** [comment]
I know I didn't select all the same options as you, but I just installed hardened version. I would think maybe it was a mirror issue, but in your log, it also could not resolve anarchy-linux.org, so that makes me think network died out during install, but I could be wrong.

![image](https://user-images.githubusercontent.com/1461924/34642156-a4b8d7a8-f2dc-11e7-8da2-6dbc65e2a57f.png)

**Comment by includes08** [comment]
Try updating to dev kernel, I never use defaults😅

**Comment by scjeti** [comment]
This still fails, for Live-Desktop , with no keyboard/mouse, when trying to boot/(install) in **uefi** mode.

**Comment by pholat** [comment]
For Live-Desktop in 1.0.0 in gui I get wrong kernel, this is uname -r shows kernel `*-9` where in /lib/modules/ there are only modules for `*-11`
I'm making iso from main branch right now and will see as it goes.

**Comment by pholat** [comment]
Upd: when made from main branch there was issue with pacstrap ( needed to remove ` -f.* ` with sed ) and then worked ok.

**Comment by JustMeErazem** [comment]
@gmcclins The GUI image is [not supported anymore](https://github.com/deadhead420/anarchy-linux/issues/766#issuecomment-451733688). Please close the issue.
