### ISSUE TITLE
Add base-devel to Utilities

### ISSUE THREAD

**Issue by BooBerry** [deadhead420/anarchy-linux#594]
Self-explanatory, add base-devel to the Utilities install software group. Would REALLY come in handy.

**Comment by AntoninCamus** [comment]
It is already possible to install base-devel, in the choice of kernel where you have choice between : 

- linux base
- linux base base-devel
- linux-lts base
- linux base base-devel
- linux-hardened (same 2 versions)
- linux zen (same 2 versions)

and I think it's more handy here. Maybe it could be in the form of a checkbox instead of having every choices 2 times.

**Comment by BooBerry** [comment]
Huh, you're right. Golly, I must be going blind because I've never noticed that before. Thanks!

Closed!
