### ISSUE TITLE
Suggestion: Add anarchy-linux.org in repro description

### ISSUE THREAD

**Issue by MarcusE1W** [deadhead420/anarchy-linux#617]
Hi.

In many repros you find the link of a more official web site like `anarchy-linux.org` right in the description of the GitHub repro on top of the `Code` tab.

Maybe that could increase (a bit) the discover ability of the web site?

Not that it is otherwise hidden but the search term `anarchy linux` currently shows the github repro before the web site...

**Comment by JustMeErazem** [comment]
@MarcusE1W This issue has been fixed since the new website is up, so please close the issue.

![Screenshot from 2019-08-09 12 27 52](https://user-images.githubusercontent.com/46302511/62773021-57f9cb00-baa1-11e9-8b9b-1626bd640edb.png)
![Screenshot from 2019-08-09 12-28-32](https://user-images.githubusercontent.com/46302511/62773024-57f9cb00-baa1-11e9-8c49-ec235443d145.png)
