### ISSUE TITLE
Installer unreadable on HiDPI screen

### ISSUE THREAD

**Issue by Prezto** [deadhead420/anarchy-linux#708]
I am trying to install on a HiDPI system, but the installers are unreadable. Is there any workaround regarding this?

I have an HP spectre with 4k screen and tried both the cli and live installers.

**Comment by Prezto** [comment]
I managed t install using an analog magnifying glass since setting vconsole and building the image didn't work for me

**Comment by JustMeErazem** [comment]
@Prezto please try the installation again in 1.0.4-cli and report back. The [ArchWiki](https://wiki.archlinux.org/index.php/HiDPI) does list a fix for the console, but it requires manually changing the settings depending on the screen size, so it would probably be hard to fix. I'll close the issue for now, since it most likey won't be fixed.
