### ISSUE TITLE
failed retrieving file 'anarchy.db' from anarchy-linux.org: 403

### ISSUE THREAD

**Issue by EvanWashkow** [deadhead420/anarchy-linux#762]
I just installed this last week. Something must have happened between then and now. Let me know when you fix this so I can install.

![screenshot from 2018-11-28 22-36-46](https://user-images.githubusercontent.com/2553816/49203781-5dbddf00-f35e-11e8-9550-4f04a9964f9f.png)

**Comment by bramkok** [comment]
The `anarchy` repository is unavailable and this breaks both the installation and update functionality of Anarchy Linux. This seems to be related to #748 that lists a todo item for removing the repository (most likely based on #711). 

These repository problems are very similar to issue #684 from a few months ago (where the same repository was offline for ~ 3 weeks).

**Sidenote:**
Since #684, I've disregarded this distro for any type of use case. I've enjoyed using _arch-anywhere_ that was later renamed to _anarchy-linux_ over the past two years and also found other Arch Linux installers/distro's that I like.
 
The *anarchy* in anarchy-linux serves as a disclaimer and warning for this distro's unreliability and instability. However I would strongly suggest to anyone who is using or is thinking about using this distro, to reconsider their choice of this distro or the option of this distro if their intended usage sitatuation expects (or even requires) any form of reliability or stability.

**Install:**
![feh_002139_000001_2018-11-29-105048_1280x800_scrot](https://user-images.githubusercontent.com/433068/49214416-e708fc00-f3c6-11e8-80ee-5db4917308dc.png)

**Update:**
![feh_005611_000001_2018-11-29-105511_840x500_scrot](https://user-images.githubusercontent.com/433068/49214417-e708fc00-f3c6-11e8-9647-fcce423bdc99.png)

**Comment by EvanWashkow** [comment]
@bramkok Thank you. I use Anarchy for a quick Arch install, and then maintain it the rest of the way from there. I usually use the anarchy repo to quickly install Pamac to get myself up and going real quick (and then disable the anarchy repo). I'll try installing without the repo, and then building Pamac from the AUR, I guess?

**Comment by bramkok** [comment]
@EvanWashkow Yes, installing Anarchy without adding the extra Anarchy repository works. Only without that quick option to bootstrap AUR.
