### ISSUE TITLE
anarchy-linux.org is down

### ISSUE THREAD

**Issue by ifl0w** [deadhead420/anarchy-linux#767]
Hello, I'd love to try anarchy Linux but sadly the website seems to be down since 10th January and I could not find any other mirror or torrent for the ISO. 

Will the website be soon up again or is there any other source for the ISO? 
Is there an easy way and documentation for making a bootable USB Stick directly from this repository?

**Comment by unixfox** [comment]
I found the `.torrent` of the ISO (here: http://torrentsearchweb.ws/40c045b157003d08444d48f97fb1b864eaeaa3d9/) and I just downloaded it on my server here: https://torrent.unixfox.eu/share/D7cvObsc

**Comment by unixfox** [comment]
I don't personally have it but I tried to recover it from web archive but sadly they didn't save it: https://web.archive.org/web/20180323061532/https://anarchy-linux.org/iso/anarchy-checksums.txt

**Comment by ifl0w** [comment]
That's bad. Thanks for the effort!

**Comment by unixfox** [comment]
When the website will be open again I'll make a mirror of it because it's not the first time that it was down and some of my friends are using anarchy.

**Comment by condor2** [comment]
- anarchy-cli-1.0.1-x86_64.iso Official Check Sums:
	* md5sum: 5a63ec2cd4421cf8bd7c05dd974e1f59
	* sha1sum: 81595f8d372ecc75fe594cf6621af3be638a2557

**Comment by Enerccio** [comment]
@unixfox thank you for this! Seriously the fuck is wrong with the website. . .

**Comment by condor2** [comment]
Domain name expired and Dylan need to pay for renew.
Now you know why: "Seriously the fuck is wrong with the website"

**Comment by Enerccio** [comment]
@condor2 wow seriously? lol

**Comment by unixfox** [comment]
Why is he not distributing the ISO using the github release feature, you can upload up-to 2GB per file on it: https://help.github.com/articles/distributing-large-binaries/?

**Comment by condor2** [comment]
@unixfox Does't have good speed for uploading.

**Comment by unixfox** [comment]
@condor2 
> @unixfox Does't have good speed for download/uploading.

What doesn't have good speed for downloading? The github server? If so it's better than having an ability to download the ISO instead of nothing.

**Comment by unixfox** [comment]
First you create a release on the project then on this page you've the ability to upload the content you want to publicly release:
![](https://i.imgur.com/iJ5EgUtg.png)

**Comment by condor2** [comment]
As I said....Dylan doesn't have good/fast internet connection.....for upload huge files

**Comment by unixfox** [comment]
How did he uploaded the ISO to the anarchy website then?

**Comment by pnedkov** [comment]
He may be building the iso on the machine that hosts the web site.

**Comment by condor2** [comment]
@unixfox 

1.0.1 is created by me and uploaded to website.

**Comment by alexandrewurtzfr** [comment]
@condor2

I downloaded your ISO and I had an error during the installation.

"ERROR: Failed to install packages to new root"
https://ibb.co/KXrysg7

Do you have an idea how to fix it? 

Thanks.

**Comment by dszryan** [comment]
> @condor2
> 
> I downloaded your ISO and I had an error during the installation.
> 
> "ERROR: Failed to install packages to new root"
> https://ibb.co/KXrysg7
> 
> Do you have an idea how to fix it?
> 
> Thanks.

apply this patch manually and try again

**Comment by NurdTurd** [comment]
oh hey @unixfox, didn't know you used Anarchy. 😄

**Comment by nickcorona** [comment]
@FredBezies Didn't work. Do you make sure that your suggestions work before you give them?

**Comment by FredBezies** [comment]
> @FredBezies Didn't work. Do you make sure that your suggestions work before you give them?

It worked a few weeks ago. Sorry it does not anymore.

Anarchy Linux is as good as dead... Really a pity :(

**Comment by Tristaan** [comment]
If possible, I can host the website for free, but no large downloads possible from my end. @unixfox suggests, it's best if the project is entirely on github. I mean, why tf not?

It can't be dead because it's a good nth-install arch iso. I use it since my third arch install. saves a lot of time if you have many pcs. Combine it with some additional scripts and you get some top shit installation automation.

**Comment by izzy** [comment]
This is the same bs like the last few times. This projects has so many flaws and just one main maintainer who can't even work effectively because of his internet speed? I mean, it's not like unsigned mirrors and all the good things weren't enough, downloads and the website almost regularly break and if something goes sideways with the maintainer the project is pretty much dead.

Am I really the only one who sees this very big, very obvious problem here?

**Comment by JustMeErazem** [comment]
@izzy, doesn't mean the project is dead. Also you can still choose to not use any of the AnarchyLinux repos and hope the development continues.

Regarding the website, since it looks pretty simple and the forums aren't used much as far as I can tell, why not just use Github Pages like @Tristaan said and release the isos as torrents and Tags/Releases?

**Comment by Arax20** [comment]
Website still down, anyway to update arch components regardless though?

**Comment by nickcorona** [comment]
Gave up on this project. It often doesn't work.

Install arch linux the old fashioned way.

**Comment by thatarchguy** [comment]
- "Domain name expired and Dylan need to pay for renew"
 - "As I said....Dylan doesn't have good/fast internet connection.....for upload huge files"

@izzy and @JustMeErazem bring up good points. It sounds like Dylan shouldn't be the sole maintainer of a project that has gained this much popularity. Can we donate money to renew the domain and migrate to github pages for hosting? Maybe we can help setup a proper build pipeline to generate the ISO as well.

**Comment by Tristaan** [comment]
Eveyone!
We have a common interest and it would be good if we could discuss this thoroughly in some chat. I have a running ts3 server on sneider.si so we can talk there, because it's easier than just commenting on an issue here on github, and I don't know exaclty how to work this out perfectly.
A proper build pipeline would be great to decrease the maintenance overhead and would help us to put all available strength into anarchy itself.

**Comment by trwnh** [comment]
limitations bound by a single maintainer? it sounds like anarchy linux could use a little more anarchy 🤔

**Comment by JustMeErazem** [comment]
@thatarchguy Dylan (deadhead420) probably owns the domain and is the owner of this project, so we should contact him first, then talk options.

**Comment by izzy** [comment]
So I've had a bit of contact with people on Facebook and if anyone is interested in maintaining a fork as a community, I've already [created one](https://github.com/monarchy-linux/anarchy-linux). 

I have two servers for mirrors(p much unlimited traffic, but they reside in Germany, so another one in the states and P/Asia would be great), a new domain isn't a problem either. I can help with containers for a build pipeline, etc. but I deffo need help with planning and the work in general(patching in other users updates, signed package repos, etc) since there is quite a bit to do. If anyone is interested in helping just drop me a mail at the organisations mail or at the [discord server](https://discord.gg/J5vduB)

**Comment by photobix** [comment]
> 
> 
> @photobix this Grub error exists for a longer time now. I only experience it on UEFI systems.

I've found out, that this error only exists while creating a swap partition. Without, It's running fine. So now I've a running Arch on my laptop, which was easy to install \o/

**Comment by pnedkov** [comment]
Is there a issue filed for the bug you were talking about which seems to me it is completely unrelated to "anarchy-linux.org is down"?

**Comment by stazeworks** [comment]
Project is alive? 
It was very useful combine for us, users!

**Comment by JustMeErazem** [comment]
@stazeworks condor2 just updated the readme with a new domain (didn't work when I checked it), so I guess he bought a new domain, just didn't set it up yet.

**Comment by stazeworks** [comment]
@JustMeErazem 
Thanks for info, I`d missed it.

I`d just download iso file ver 1.0.1 from torrent tracker. Can I install it right now or I will get some errors?

**Comment by JustMeErazem** [comment]
@stazeworks You'll probably get some errors, update the installer: `anarchy -u` and check other issues for possible fixes. If I were you I'd wait until a new version is released or compile the ISO myself so the packages would get updated.

**Comment by eirenicon** [comment]
http://archive.org (the wayback machine/ Internet Archive) provides free space, huge bandwidth all at no-cost
