### ISSUE TITLE
Error: Fail to install packages to new root

### ISSUE THREAD

**Issue by leandroechevarria** [deadhead420/anarchy-linux#789]
Hello, today I tried to install with this script in a Virtualbox VM and it failed. Things I selected along the way:
- EN language, en_US locale
- LTS Kernel
- Auto partition
- Gnome desktop
- Additional software: tmux, mongodb, postgres, scrot, vim, neovim.
Also I downloaded the ISO today from the webpage and updated the script before run it.

Here's the log:
![Screenshot_3](https://user-images.githubusercontent.com/45211582/57183261-90758180-6e80-11e9-998a-382e6a4aa580.png)

Have a good weekend.

**Comment by MaxNeuron** [comment]
Before starting the installer, try this:

`# anarchy -u && pacman -Syy archlinux-keyring && anarchy`

In this way anarchy is updated, the keyring is installed and the installer starts, all in a single command.

**Comment by leandroechevarria** [comment]
Tried those commands but same error:

![Screenshot_4](https://user-images.githubusercontent.com/45211582/57185588-d8a69b00-6ea4-11e9-98f6-fa9154ef5f3f.png)

**Comment by MaxNeuron** [comment]
It seems to be an error when wanting to install `mongodb`. What happens if you do not select additional software? In case the operating system is installed, you can add the necessary packages later.

**Comment by leandroechevarria** [comment]
Yes I will ask if that way is also "correct" in terms of this installer. If I don't select any additional software (or at least any additional software that fails like mongodb), the instalation ends well.
If this problem with packages like mongo are not caused by the installer itself, we can close the issue I think.

**Comment by LeFlawk** [comment]
Hey, same thing happens to me but with the qt4 package. No additional software selected.

**Comment by leandroechevarria** [comment]
@LeFlawk Last week I went into that same error but I can solve it doing the instructions here (but with the qt4 package) https://github.com/deadhead420/anarchy-linux/issues/777

Hope it works for you too.

**Comment by MaxNeuron** [comment]
@leandroechevarria the Arch Linux Wiki says that _MongoDB has been removed from the official repositories due to its re-licensing issues [[1]](https://lists.archlinux.org/pipermail/arch-dev-public/2019-January/029430.html)._ The installer offers you additional software from the official repositories, that's why I gave you an error.
However, you can install `mongodb` from the [AUR](https://wiki.archlinux.org/index.php/MongoDB#Installation).
I just made an pull request (#790) so that MongoDB is removed from optional software list.
I think the thread can be closed.

**Comment by leandroechevarria** [comment]
@MaxNeuron Nice, thanks for the info. Hope that pr will be merged soon.

I'm closing this issue.
